### ISSUE TITLE
How do partials work for mustache?

### ISSUE THREAD

**Issue by eliOcs** [tj/consolidate.js#107]
Hi,

I've been looking for documentation on partials and I can't find any recent source of how to set up partials using consolidate with mustache.

For example if I have the following views:

```
* views/
    - index.mustache
    * partials/
        - partial.mustache
```

And `index.mustache` is defined as:

```
<html>
    {{> partials/partial }}
</html>
```

How can I set up express using consolidate to render `index.mustache`?

How can I tell consolidate to look for the partial `views/partials/partial.mustache` when I use the mustache partial `{{> partials/partial}}`?

Thanks for your help in advance.

**Comment by ianstormtaylor** [comment]
Is there any better information on how to get this working? Slamming my head against my keyboard right now trying to get Consolidate and Mustache working together with partials... the documentation is practically nonexistent.
