### ISSUE TITLE
Getting hold of local engines

### ISSUE THREAD

**Issue by SBoudrias** [tj/consolidate.js#110]
Some templating engine allow global settings. For example, Handlebars allow registering helpers.

Right now there's no way to get the local engine instances and use them.

I think a basic implementation could be this one. Although I saw that for some engines have some particularities as to how they're required, so this wouldn't work in all case. I'm just not sure how complicated such a function should be, we could also simply add a `get` method to every template engines so each one can stay unique...

```javascript
/**
 * Get local template engine reference
 *
 * @api public
 */

exports.get = function(name){
  var engine;
  try {
    engine = requires[name] || (requires[name] = require(name));
  } catch(err) {
    throw new Error("Tying to get Unknown engine");
  }

  return engine;
};
```

**Comment by doowb** [comment]
the `requires` object is now exposed so you can require in your engine and add what you need, then add it on the `requires` object to be used later.

Here's an [example in the readme](https://github.com/tj/consolidate.js#template-engine-instances)
