### ISSUE TITLE
"Module not found" inside a parent using `npm link`

### ISSUE THREAD

**Issue by timoxley** [tj/consolidate.js#130]
This is probably not fixable but I just thought I'd leave this here for anyone else wondering why their code using `npm link` doesn't work.

Consider this situation:

* app depends on `swig` & `splinky`.
* `splinky` depends on `consolidate` (but not `swig`).
* app uses `splinky` to configure `swig` as a template engine via `consolidate`
* `consolidate` tries to require `swig`

In a hard links hierarchy, this works fine, `consolidate` happily resolves `swig`, but if you happen to use `npm link` on `splinky`, then `splinky` can no longer locate the `swig` installed in the parent application: `Cannot find module 'swig'`

Related issue in node: https://github.com/joyent/node/issues/4757

This kinda sucks since AFAIK `npm link` otherwise works transparently. I'm not quite sure the reasoning why symlinked modules don't look in their parent:

>  symlink modules look for modules relative to their realpath'ed locations

Probably makes sense now I think about it for a bit.

**Comment by erwan** [comment]
Is there an alternative to npm link that works, without having to publish an unfinished package?

**Comment by doowb** [comment]
You can push your package to a github branch and install via npm with:

```sh
$ npm i user/repo#branch -S
```
Where `user` is the owner of the repository, `repo` is the repository and `branch` is the branch it lives on. Doing `-S` or `-D` will include it in `package.json` and resolve to the repository instead of the npm version.

This lets you work on your project without having to publish it.

**Comment by BridgeAR** [comment]
Well as we can't do anything about this, I'll close the issue. Thanks for reporting it though.
