### ISSUE TITLE
[could I sent a PR for: ] Configure custom require context

### ISSUE THREAD

**Issue by mikermcneil** [tj/consolidate.js#135]
So I have a project at `/foo` with `bar` as a dependency in `/foo/node_modules/bar`.  If I run `npm install ejs` in `/foo`, I'll get `/foo/node_modules/ejs`.  But let's say `bar` wants to have `consolidate` as a dependency, so that the app at `/foo` doesn't have to do anything special.

Currently, in Sails, @sgress454 and I are [bundling a monkey-patched version of consolidate](https://github.com/balderdashy/sails/blob/v0.10/lib/hooks/views/consolidate.js#L9).  Despite being annoying/risky to maintain, it makes me feel all funny inside.  One option I considered is temporarily overriding `module.require` (ie. https://npmjs.org/package/proxyquire), but this would also be a bit of a hack.

@visionmedia Would you be down if I sent a pull request with a patch to provide a usage of consolidate that makes the base require path configurable? Backwards-compatible, lightweight, tests, etc.  Also, if you have another way you'd prefer to see this done, I'm all ears, and happy to try to help.  Thanks!

**Comment by yoshokatana** [comment]
Already done! :3

[Here's an example](https://github.com/nymag/multiplex-templates/blob/master/index.js#L11). Coincidentally, I'm also using proxyquire in my tests!

**Comment by yoshokatana** [comment]
(By "already done", I guess I mean done a year after you opened the ticket. I should really check date stamps before replying to issues)

**Comment by doowb** [comment]
Sounds like this was resolved, I'm going to close but please feel free to reopen or create a new issue if:
- the bug is still happening
- you're still having problems
