### ISSUE TITLE
Layout support for handlbars

### ISSUE THREAD

**Issue by AlexBezuska** [tj/consolidate.js#163]
Hi, would you accept a pull request to add layout support for handlebars? Are you opposed to adding layout support to consolidate.js?
I am trying to get something like this working:
```js
app.get("/home", function(req, res) {
	res.render("home", {
		layout: "main",
		title: "hello world",
		test: test
	});
});
```
  Thanks.

**Comment by doowb** [comment]
I think it's better to support features exposed by the template engine and not add additional functionality in consolidate.

Check out [this handlebars layouts library](https://github.com/shannonmoeller/handlebars-layouts) if you're interested in adding layouts to handlebars.
