### ISSUE TITLE
Partials with Hogan not requiring explicit configuration

### ISSUE THREAD

**Issue by shrikeh** [tj/consolidate.js#164]
I'm not sure if this is a documentation issue, or has been previously solved, however n hour of Googling and a brief skim of the issues hasn't helped.

End goal: I set a partials directory in the consolidate or app, and then do not have to pass the partials I require in the controller. I have seen an example with the following:

```
  app.set('partials', path.join(views_dir + '/partials/'));
```

However this does not seem to work. I don't think having to pass the exact partial in the controller is necessarily useful from maintainability; it would be better if this was an override if consolidate was unable to locate a partial that matched {{>footer}}, for example.

**Comment by doowb** [comment]
You'll have to set the paths to each partial explicitly for `consolidate` to find them. Some apps might implement this and that could be the example you saw.
