### ISSUE TITLE
Separate view data and options

### ISSUE THREAD

**Issue by garygreen** [tj/consolidate.js#170]
Currently to pass custom options to an engine it's passed in the `options` -- the options is passed as the view data onto the engine, it means you can't have view data with the same attributes as the options. Ideally these two should be separated like so:

**Current**

```
exports.nunjucks.render = function(str, options, fn) {
    //
}
```

**Proposed**

```
exports.nunjucks.render = function(str, data, fn, options) {
    //
}
```

Where the options specific for the engine are not part of the view data (optional parameter)

Or alternatively possibly just a general options where you can have the done & fail callbacks, with any custom options:

**Alternative Proposal**

```
exports.nunjucks.render = function(str, data, options) {
    // options.done -- called with the rendered view data
    // options.fail -- called when rendering failed with error message
    // can pass custom options e.g. options.loader (for nunjucks)
}
```

Of course these changes will break backwards compatibility, but it's definitely something worth considering for a major version bump.

**Comment by kevinschaul** [comment]
This would be a great improvement.

**Comment by roll** [comment]
No options for nunjucjk for now?
