### ISSUE TITLE
consolidate 0.11.0 error

### ISSUE THREAD

**Issue by craigbeck** [tj/consolidate.js#184]
TypeError: Object #<Object> has no method 'compileFile' at View.exports.jade [as engine]
    (/app/node_modules/consolidate/lib/consolidate.js:286:56) at View.render 
    (/app/node_modules/express/lib/view.js:76:8) at Function.app.render 
    (/app/node_modules/express/lib/application.js:503:10) at ServerResponse.res.render 
    (/app/node_modules/express/lib/response.js:802:7) at ServerResponse.render 
    (/app/node_modules/newrelic/lib/instrumentation/express.js:105:21) at Object.exports.init [as handle]
    (/app/services/admin/drywall/views/login/index.js:8:9) at next_layer
    (/app/node_modules/express/lib/router/route.js:103:13) at Route.dispatch
    (/app/node_modules/express/lib/router/route.js:107:5) at
    /app/node_modules/express/lib/router/index.js:205:24 at Function.proto.process_params
    (/app/node_modules/express/lib/router/index.js:269:12)

Used with jade 1.0.2.

Not sure as to the issue, but reverting back to consolidate 0.10.0 resolved.

**Comment by doowb** [comment]
`0.11.0` is tested with `jade 1.9.1` and it looks like `compileFile` was added in `jade 1.5.0`.

Thanks for pointing it out. These are the type of issues I expected and is why I bumped to `0.11.0`
