### ISSUE TITLE
not supported filters and extensions in nunjucks

### ISSUE THREAD

**Issue by randomailer** [tj/consolidate.js#185]
I have a problem, consolidate not supported filters and extensions in nunjucks

**Comment by doowb** [comment]
@randomailer will #168 help with this? If not, can you submit a PR that will enable this?

**Comment by yoshokatana** [comment]
#168 will fix this, since devs will be able to do `cons.requires.nunjucks.addFilter()` etc to the nunjucks instance directly.

**Comment by yoshokatana** [comment]
PR: #187

**Comment by doowb** [comment]
@randomailer see the comment in #187.

I'm going to close this since it can be achieved using the `requires` object. If some wants to create a PR that allows passing filters and extensions through the options to make it easier to set up, I'm open to that.
