### ISSUE TITLE
Add support for Twig package?

### ISSUE THREAD

**Issue by slavafomin** [tj/consolidate.js#192]
Hello!

It would be great if we could use Consolidate with Twig: https://github.com/justjohn/twig.js.

Is it hard to implement? Are there any drawbacks?

Thanks!

**Comment by RobLoach** [comment]
Just added it to [JSTransformers](https://github.com/jstransformers): [`jstransformer-twig`](https://github.com/jstransformers/jstransformer-twig). The Consolidate API is quite similar to JSTransformer's.

**Comment by madeofpeople** [comment]
@RobLoach sounds relevant to our project ;D

**Comment by RobLoach** [comment]
https://github.com/tj/consolidate.js/pull/216
