### ISSUE TITLE
Add support for Liquid-Node package?

### ISSUE THREAD

**Issue by stunjiturner** [tj/consolidate.js#198]
Hi ,

Can we get support for the Port of the Liquid template engine to Node.js (with support for asynchrony through Promises)
sirlantis/liquid-node

**Comment by cameronjroe** [comment]
+1

**Comment by BridgeAR** [comment]
Please feel free to open a PR for this. I'm going to maintain the lib as good as possible but I doubt that I'll find the time to add new things on my own anytime soon.

**Comment by BridgeAR** [comment]
@cameronjroe Is the API the same for liquid-node and tinyliquid?

**Comment by cameronjroe** [comment]
@BridgeAR It actually looks like it's better than tinyliquid. I've been having trouble with tinyliquid because all the features of liquid aren't actually supported. liquid-node says it has full liquid support.

**Comment by BridgeAR** [comment]
Well, I'd like to support liquid-node and require it if tinyliquid is not available. But if the API differs, it'll need another implementation than tinyliquid and we need to improve the tests by testing the fallback libraries too (this can be done but needs some work with the tests).

**Comment by cameronjroe** [comment]
If can look into adding a PR, but why would it need a fallback? Could it just be replaced with liquid-node?

**Comment by cameronroe** [comment]
Any update on this?

**Comment by cameronroe** [comment]
Tinyliquid is having a lot of bugs, can this be merged in at some point soon?

**Comment by cameronroe** [comment]
Any update on this?

**Comment by doowb** [comment]
Released in 0.15.0.
