### ISSUE TITLE
Documentation on partials

### ISSUE THREAD

**Issue by ismay** [tj/consolidate.js#204]
From the documentation it isn't clear to me how the paths to partials are resolved. If I pass a partials object as `options.partials`, how will consolidate resolve the paths to these partials?

And (how) does the resolving of these paths differ when I use the `.render` method instead of `cons[engine]()`?

**Comment by doowb** [comment]
The paths are resolved relative to the template being rendered. So if your `home.hbs` template is in `views`: `./views/home.hbs`, you can put your partials in `views/partials` and name all of your partial keys like `partials/nav.hbs`:

So `nav.hbs` will be in `./views/partials/nav.hbs`.

If you're using `.render` directly, then you should add your partials with the `key: content` the way you want them registered. By using `.render` directly, you're skipping over the `.readPartials` method.

**Comment by ismay** [comment]
Ah ok, that makes sense. Thanks for explaining!

**Comment by doowb** [comment]
np, closing. Re-open if you think you need more explanation.
