### ISSUE TITLE
API to add filters?

### ISSUE THREAD

**Issue by slavafomin** [tj/consolidate.js#205]
Is there an API to add filters to the underlying templating engine?

If not, I think it would be a very useful feature.

**Comment by doowb** [comment]
You can add filters with the template engine's api that you're using, then set the engine on the `.requires` property. There's an example using `swig` here: [template engine instances](https://github.com/tj/consolidate.js#template-engine-instances)

**Comment by slavafomin** [comment]
I thought that the purpose of "consolidate" was to establish a single API for all templating engines, does it not? In my opinion view filters are pretty much the very public part of any templating engine's API.

For example Sails.js framework is using Consolidate to provide views for it's MVC. It would be unreasonable to implement the consolidation code in the Sails itself or to create yet another consolidate module just for for view filters consolidation. I firmly believe that this logic belongs to Consolidate.js.

P/S: Why are you guys always closing the issues without even discussing it first? What's happening to the OpenSource principles? Is it becoming a read-only open source movement? )

**Comment by doowb** [comment]
I misunderstood the question. I think the API is normalized for rendering, however, some of the engine wrappers do implement options (like `helpers` and `partials`). I'll reopen and if you're interested in submitting a PR that implements `filters` for engines that accept `filters` works for me.

**Comment by slavafomin** [comment]
Thank you Brian! I will discuss this problem with Sails.js developers and if this feature will get a green light I will look into this problem from the Consolidate point of view. If someone is willing to contribute to this effort, I will gladly accept any feedback, ideas, code, etc.

**Comment by doowb** [comment]
Closing since `filters` are usually an `engine` specific implementation similar to `helpers`. For any engines that support `filters`, we'll accept PRs to implement that option for those engines.
