### ISSUE TITLE
problem non-.liquid files with "extends" using tinyliquid

### ISSUE THREAD

**Issue by soswow** [tj/consolidate.js#214]
Looks like project is dead, but just in case it will be resurrected:
```javascript
var basename = path.basename(name);
var extname = path.extname(name) || '.liquid';
var filename = path.join(includeDir, basename + extname);
```
If you have `default.html` as input here, then output will be `default.html.html`

**Comment by doowb** [comment]
@soswow will you add a test to reproduce this and update the code in a PR? I've been busy with work and have missed some of the more recent issues/PRs here, but I'll make some time to address them.
