### ISSUE TITLE
ejs and jade use together by consolidate

### ISSUE THREAD

**Issue by GabrielchenCN** [tj/consolidate.js#217]
i am a beginner for nodejs ，i try to combine ejs and jade together used by consolidate.  but i confused that because
it’s working on one project before and not working on other project now.
	codes like：
	var engines = require('consolidate'); 
	 app.engine('jade', engines.jade); 
	 app.engine('html', engines.ejs);
	 app.set('view engine', 'jade'); 
	 app.set('view engine', 'html'); 
	 app.disable('x-powered-by'); 
	 app.set('port', config.port); 
	 app.set('views', path.join(__dirname, 'views'));
     // i used the frame named “drywall”
    but if codes like this it work,but not my desired effect,because not work together.
	
       var engines = require('consolidate'); 
	 app.engine('jade', engines.jade); 
	// app.engine('html', engines.ejs);
	 app.set('view engine', 'jade'); 
	 //app.set('view engine', 'html'); 
	 app.disable('x-powered-by'); 
	 app.set('port', config.port); 
	 app.set('views', path.join(__dirname, 'views'));
 my version :
1. "express": "^4.12.x",
2. ejs”version": "2.3.3",
3.jade  "version": "1.9.2",
4.”consolidate":"version": "0.13.1",
  can you help me ? 
  thanks

**Comment by GabrielchenCN** [comment]
i fixed the problem by using  this  expression:
// var engines = require('consolidate');

// app.engine('jade', engines.jade);
// app.engine('html', engines.ejs);
//it's worked!
app.engine('jade', require('jade').__express);
app.engine('html', require('ejs').renderFile);

app.set('view engine', 'jade');
//app.set('view engine', 'html');

who can tell me why?

**Comment by BridgeAR** [comment]
You can only set the view engine once. This is how express works.

So this should work as intended:
```js
var engines = require('consolidate');

app.engine('jade', engines.jade);
app.engine('html', engines.ejs);

app.set('view engine', 'jade');
```
