### ISSUE TITLE
tinyliquid customTags not working

### ISSUE THREAD

**Issue by cameronjroe** [tj/consolidate.js#219]
I'm not able to rendering this with consolidate using tinyliquid:

```
import tinyliquid from 'tinyliquid'

var customTags = {};
  
customTags.picture = function (context, name, body) {
  var tpl = '<div>Test</div>';
  var ast = tinyliquid.parse(tpl);
  context.astStack.push(ast);
};

export default customTags;
```

**Comment by cameronjroe** [comment]
Any ideas on why this might not be working?

**Comment by cameronjroe** [comment]
?

**Comment by BridgeAR** [comment]
I did not look into it at all, so no.

**Comment by cameronroe** [comment]
Gave this another go. It's still not working. I disabled the cache. Any ideas?

**Comment by cameronroe** [comment]
// config.js
export default {
  content_for_layout: function (body) {
    return 'Hello!';
  }
}

// used as 

// import customTags from './config';
// {
//    customTags: customTags
// }

**Comment by cameronroe** [comment]
?
