### ISSUE TITLE
lodash support broken when using lodash > 2

### ISSUE THREAD

**Issue by mlaccetti** [tj/consolidate.js#220]
`_.template` changed from 2.4 to 3+ from `_.template(text, data, [options], [sourceURL], [variable])` to `_.template([string=''], [options])`, so the https://github.com/tj/consolidate.js/blob/master/lib/consolidate.js#L782 `engine.template(str, null, options)` call is wildly broken.  It'll have to change to `engine.template(str, options)` instead.

Of course, this assumes the use of lodash 3+; if folks are still using an older version, party times ahead!

**Comment by BridgeAR** [comment]
Thanks for pointing this out. It is actually just broken in lodash 4, as it was deprecated in v.3 and removed in v.4. And the templating will still work, but you can't pass any options to lodash in v.4.

Right now the tests still pass, as there are no options tests right now and this is the main issue in my opinion. It would be very helpful if you could open a PR to add some tests. I try to maintain this library as good as it is possible but I do not have any time right now to add new things like the tests.
