### ISSUE TITLE
twig is not sorted in devDependencies

### ISSUE THREAD

**Issue by stealthybox** [tj/consolidate.js#233]
In the `package.json`, `twig` is out of order:
```
...
    "swig": "^1.4.1",
    "templayed": ">=0.2.3",
    "twig": "^0.8.2",
    "tinyliquid": "^0.2.22",
    "toffee": "^0.1.12",
    "underscore": "^1.3.3",
...
```
installing new dependencies with npm using `--save` `--save-dev` `-S` or `-D` will sort the depency hashes into alphabetical order, so we should fix this typo.

**Comment by BridgeAR** [comment]
Fixed
