### ISSUE TITLE
[feature request] Add support for Marko

### ISSUE THREAD

**Issue by insanetisane** [tj/consolidate.js#235]
Would be awesome if someone with know-how could add [marko](http://markojs.com/) support.
Looks like a great high speed, clean, full-featured templatting language.

**Comment by BridgeAR** [comment]
If you open a PR I'll gladly have a look at it and merge it.

**Comment by nor-bu** [comment]
Any update on this?

**Comment by jdnichollsc** [comment]
+1

**Comment by hoichi** [comment]
For the record, here’s a PR with an update for Marko v4: https://github.com/tj/consolidate.js/pull/281
Not sure I like what I’ve done with tests, so maybe there’ll be more updates before it gets merged.

**Comment by doowb** [comment]
Released in 0.15.0.
