### ISSUE TITLE
partials confusion

### ISSUE THREAD

**Issue by siddo420** [tj/consolidate.js#252]
Its a quick question regarding HBS partials. I have already seen other issues on the topic but still couldn't figure out.

I put my partials in views/partials but when I call them in Handlebars templates I get errors like 

"Error: The partial BackButton could not be found".

I am using Express and here is my server side code (relevant lines)
```
...
app.engine( 'hbs', cons.handlebars                 );
app.set( 'view engine', 'hbs'                      );
app.set( 'views',       __dirname + '/www/views' );
...
...
app.get( '/', function( req, res ){
  res.render( 'index', {
    html_header: 	'......'
  });
}); 
```

Where should I make changes and add options.partials etc?

**Comment by pomeo** [comment]
```
app.get( '/', function(req, res) {
  res.render( 'index', {
    partials: { BackButton: 'partials/BackButton' }
  });
});
```

**Comment by siddo420** [comment]
Thanks.

**Comment by progand** [comment]
You should add this to docs. It was nearly impossible to figure out how to use partials within `render()` function
