### ISSUE TITLE
Nunjucks: disabling cache doesn't work

### ISSUE THREAD

**Issue by jvolker** [tj/consolidate.js#254]
I'm using Nunjucks in `metalsmith-layouts` based on `consolidate.js`.
It seems like `cache: false` doesn't have any effect on any files being used with Nunjucks' `include`, which are cached by default.

I already described the problem at [metalsmith-layouts](https://github.com/superwolff/metalsmith-layouts/issues/108), but was referred to consolidate.

In Nunjucks the caching option is called `noCache` instead of `cache`. Could that cause the problem?

Thanks!

**Comment by RyanZim** [comment]
@jvolker Why can't you pass `noCache: true` in the options?

**Comment by jvolker** [comment]
@RyanZim No, that unfortunately didn't work. Configuring nunjucks directly with `watch: true` or `noCache : true` worked though.

But I also thought consolidate.js was made to unify these different configurations to the same API?

**Comment by RyanZim** [comment]
Looking at the source code, it looks like you'll have to do something like this:

```
cons.nunjucks(path, {
  // Locals
  settings: {
    views: {
      noCache: true
    }
  }
}, cb);
```
Source: https://github.com/tj/consolidate.js/blob/master/lib/consolidate.js#L1094.

> But I also thought consolidate.js was made to unify these different configurations to the same API?

It is an _attempt_. Cache control is sort of a sore spot IMO. FWIW, you might also want to look at https://github.com/jstransformers/jstransformer (haven't tried it in production yet).

If this solves your problem, please close this issue. Thanks!
