### ISSUE TITLE
Cannot find module 'nunjucks'

### ISSUE THREAD

**Issue by jojocague** [tj/consolidate.js#262]
> app.js

var express  = require('express');
var app      = express();
var path = require('path');
var cons = require('consolidate');
var mainPage = require('./routes/mainPage.js')

app.engine('html', cons.nunjucks);
app.set('views', path.dirname(__dirname)+'\\frontend\\view');

app.use(express.static(process.cwd()+'\\production\\frontend'));

app.use('/', mainPage);

app.listen(3000, function () {
  console.log('Example app listening on port 3000!');
});

---------------------------------------------------------------------------------------------
and I get console error:

`Error: Cannot find module 'nunjucks'`

how i can resolve this ???

**Comment by babinslava** [comment]
You had to install nunjucks -
`npm install nunjucks`

**Comment by faithererer** [comment]
thanks,im a sb
