### ISSUE TITLE
Can I add a lib which requires java environments ?

### ISSUE THREAD

**Issue by int64ago** [tj/consolidate.js#266]
Hi,
  [FreeMarker](http://freemarker.org/) is a popular Java template engine, I create a [NodeJS version](https://github.com/int64ago/freemarker) with [FMPP](http://fmpp.sourceforge.net/) integrated. Now it can work well, so I want to add it to consolidate.js. But the problem is that the test may be failed if no java environments, do you welcome such library? Or is there another way?

Thanks a lot :-)

**Comment by doowb** [comment]
@int64ago if you'd like to submit a PR, we can review it.

> But the problem is that the test may be failed if no java environments

I think if you set up tests in your nodejs version and run them on continuous integration services like travis-ci and appveyor, we can determine if they'll run here.

I'm going to close this issue for now, but feel free to submit a PR.
