### ISSUE TITLE
routes partials in common

### ISSUE THREAD

**Issue by roccomuso** [tj/consolidate.js#276]
I'm using mustache with consolidate.
I have multiple routes using the same partials.
I wanna avoid having duplicate code, so I'm using a var containing the partials paths:

```javascript
var commonPartials = {
  head: 'partials/header',
  footer: 'partials/footer'
}

router.get('/hello', function (req, res) {
  res.render('hello', {
    partials: commonPartials,
    title: 'Hello',
    pid: process.pid
  })
})

router.get('/world', function (req, res) {
  res.render('world', {
    partials: commonPartials,
    title: 'World',
    pid: process.pid
  })
})
```

The issue is that on the second call of a route, the obj are populated with the whole partial file giving an error like this:

```
Error: ENOENT: no such file or directory, open '/home/user/Desktop/REPOS/HelloWorld/views/<footer class="footer">
  <div class="container">
    <div class="content has-text-centered">
      <p>
      ...
```

What's the best way to handle this issue and sharing partials to avoid duplicated code?

**Comment by TunpixelCEO** [comment]
facing the same issue

**Comment by doowb** [comment]
@roccomuso sorry for the late response.

For now, you can ensure your `commonPartials` object is not modified by passing a copy to `.render`:

```js
res.render('world', {
  partials: Object.assign({}, commonPartials),
  title: 'World',
  pid: process.pid
});
```

I'm working on some updates and I'll include this natively so the contents are still cached, but not on the source object.
