### ISSUE TITLE
why it doesn't support vue?

### ISSUE THREAD

**Issue by oqq5518** [tj/consolidate.js#283]
why it doesn't support vue?

**Comment by snowdream** [comment]
＋1

**Comment by snowdream** [comment]
https://github.com/vuejs/vue/issues/5897

**Comment by akhoury** [comment]
why was this closed?

**Comment by akhoury** [comment]
oh well https://github.com/tj/consolidate.js/pull/315

**Comment by doowb** [comment]
@akhoury thanks for the PR, I was just about to suggest a PR to add vue support :)
