### ISSUE TITLE
Path to pass in when using consolidate for app.engine?

### ISSUE THREAD

**Issue by ThomasPCG** [tj/consolidate.js#301]
I'm doing this...

```
app.engine('html', engines.handlebars({
    helpers: handleBarHelpers
}));
```
but apparently it's failing because there is a path which I need to specify?

UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot set property 'filename' of undefined

I can't find any API for the constructors above in the documentation. Can anyone guide me to the right place for this?

**Comment by doowb** [comment]
There's [this example on the readme using express](https://github.com/tj/consolidate.js#express-3x-example).

Also, the [express](https://expressjs.com/) documentation has a lot more information on how to use template engines. [Here's a guide specifically for that](https://expressjs.com/en/guide/using-template-engines.html)

BTW... what you're doing in the code above is calling the `handlebars` engine directly, which is attempting to render something. Instead, just use this line:

```js
app.engine('html', engines.handlebars);
```

Then see the `express` documentation for setting the `views` path and how you can pass `helpers` to the engine when rendering (I think you can add them as locals... `app.locals.helpers = handleBarHelpers;` but I'm not positive).
