### ISSUE TITLE
How can I set a default layout for handlebars in sails js?

### ISSUE THREAD

**Issue by Ghusar** [tj/consolidate.js#312]
I am using sails 1.0 in my project. Since sails has dropped support for layout in sails 1.0. I am using consolidate to render my views. I cannot find a documentation for setting up a default layout for entire application using consolidate?

**Comment by doowb** [comment]
`Handlebars` does not handle layouts directly, which is probably why `sails` used to support it. `consolidate` also doesn't handle layouts so you'll probably have to find another solution.

You can try the [layouts](https://github.com/doowb/layouts/) module to pre-apply layouts to your views, then pass those to `consolidate`. I'm not sure what `sails` exposes to allow this or if it's possible, but it might be worth looking into.

**Comment by Ghusar** [comment]
Thanks you for quick response. I appreciate your help.

**Comment by Ghusar** [comment]
Hi Brian,
I raised a issue for consolidatejs about supporting layouts for handlebars.
Since there was no feature implemented about it, I was thinking should
consolidate move forward in that direction to support everything that a
view engine needs that can be easy to setup using any kind of framework.If
so I am happy to contribute for that.
Please reply with your thoughts

Regards
Hardik Ghusar
