### ISSUE TITLE
It is not possible to customize Twing environment

### ISSUE THREAD

**Issue by ericmorand** [tj/consolidate.js#329]
Current Twing support prevents customizing the environment or even passing a totally custom environment - which is needed to add extensions for example.

I can fix that but that'll create a breaking change for current users of Consolidate that use this engine.

What is the policy of Consolidate about this?

**Comment by doowb** [comment]
@ericmorand take a look at the [Nunjucks](https://github.com/tj/consolidate.js/blob/31cfe787b2642db9d7dd0ff06c6e02ec50d1c701/lib/consolidate.js#L1317) implementation. Is it possible to do something similar with `Twing`?

I haven't had a chance to publish the new version of `consolidate` that includes `Twing` yet, so the only breaking change would be if someone is using `consolidate` from GitHub.

So, please submit a PR with your changes.

**Comment by credomane** [comment]
Just ran into this issue myself. Spent way too long trying to debug `TwingErrorLoader: Template "layout.twig" is not defined` only to eventually discover it is a problem with consolidate's twing handling. A twig is rendered from a string with a null loader and thus can't include other twig templates.

I'll take a look at the nunchuck implementation and see what I can come up with.
