### ISSUE TITLE
Mustache support is broken since mustache v4 release

### ISSUE THREAD

**Issue by vladimyr** [tj/consolidate.js#331]
⚠️ `consolidate` internally uses `mustache.to_html()` ([source](https://github.com/tj/consolidate.js/blob/f974b92/lib/consolidate.js#L1103-L1112)) that got removed in `v4`: https://github.com/janl/mustache.js/blob/aca97b8/CHANGELOG.md#400--16-january-2020

Original `to_html` implementation can be seen here:
https://github.com/janl/mustache.js/pull/735/files#diff-634d226b45dfff37e6e48538dbfe4cb0L730-L742
which clearly indicates that it can be safely replaced with `mustache.render` call.

Reading through issues I got under impression that this package is effectively unmaintained (#292) but if you have any free time I believe this is something that needs your (immediate) attention @doowb

**Comment by doowb** [comment]
PRs are welcome.

**Comment by vladimyr** [comment]
Hopefully it will get published to npm soon 🤞

**Comment by alemangui** [comment]
Hey there, any news on a release containing this fix anytime soon?

**Comment by vladimyr** [comment]
> Hey there, any news on a release containing this fix anytime soon?

Join the waiting party 🥳 
The last release was 2yrs ago: https://github.com/tj/consolidate.js/releases/tag/0.15.1 🤷
