### ISSUE TITLE
Error: Can't resolve 'atpl'

### ISSUE THREAD

**Issue by daolou** [tj/consolidate.js#334]
https://bundlephobia.com/result?p=@jsany/cli-kit

Stacktrace: 

```sh
ModuleNotFoundError: 
Module not found: 
Error: Can't resolve 'atpl' in '/tmp/tmp-build/packages/build-@jsanycli-kit-0fE/node_modules/consolidate/lib'
```

![image](https://user-images.githubusercontent.com/22312092/90356493-48349f80-e082-11ea-8377-280c09bf105d.png)

this error due to badge throw bundlephobia inaccessible

detail: <https://github.com/pastelsky/bundlephobia/issues/387>

**Comment by jbcastro** [comment]
I had this problem, it stemmed from Visual Studio Code. I was writing "const" but it took that as autocomplete or something as "cons" so it added "import cons from "consolidate";" to the top of my file. I finally figured it out by deleting the consolidate folder from node_modules, it then pointed to which component file was showing "import cons from "consolidate";" at the top.

So delete consolidate folder from node_modules, find what file is asking for "import cons from "consolidate";", delete that line. And if you're so inclined do NPM install again.
