### ISSUE TITLE
help with  dust partials onLoad method

### ISSUE THREAD

**Issue by lundin** [tj/consolidate.js#53]
Hi, trying to get the partials to work, but why am i unable to set the the path for the engine.onLoad in here:

consolidate.js (inside exports.dust)
```js
engine.onLoad = function(path, callback) {  console.log(path);read(path, options, callback); }
```

hard code the path does make it work, i just dont understand how should i pass the path to onLoad method from my express app ?

app.js
```js
cons = require('consolidate')

var app = express();

cons.dust('/home/expressapp/views/page1.dust',{ cache: true }, function(err, html){
  if (err) throw err;
  console.log(html);
});
cons.dust('/home/expressapp/views/page2.dust',{ cache: true }, function(err, html){
  if (err) throw err;
  console.log(html);
});
app.engine('dust', cons.dust);
```
index.dust

```dust
<div id="wrapper">
    <div id="header">
        <div class="logo"></div>

    {>page1/}
    {>page2/}
```

......

trying this ends up in 500 Error: ENOENT, open page1 as there is no path.

**Comment by doowb** [comment]
I think this is solved because the `dust` implementation has an `onLoad` method added to it. There shouldn't be a need to pre-loaded partials.
