### ISSUE TITLE
500 Error: ENOENT, open 'C:\Users\Gilbert\Documents\GitHub\maths4me\base.dust'

### ISSUE THREAD

**Issue by gilbertbw** [tj/consolidate.js#56]
I get this error when trying to set up inheritance in dust.js with consolidate.js:

```
500 Error: ENOENT, open 'C:\Users\Gilbert\Documents\GitHub\maths4me\base.dust'
```

I have a file called index.html:

``` html
{>"base.dust"/}
   {<title}Hi{/title}
```

Which calls base.dust:

``` html
<!DOCTYPE html>
<html>
  <head>
    <title>{+title}Maths 4 me{/title}</title>
    <link rel='stylesheet' href='/stylesheets/style.css' />
  </head>
  <body>
    <h1>Hi</h1>
    <p>Welcome to maths4me</p>
  </body>
</html>
```

**Comment by doowb** [comment]
Sounds like this was resolved, I'm going to close but please feel free to reopen or create a new issue if:
- the bug is still happening
- you're still having problems
