### ISSUE TITLE
Relative path partials in dust

### ISSUE THREAD

**Issue by jmoyers** [tj/consolidate.js#66]
Based on this:
https://github.com/visionmedia/express/blob/master/lib/view.js#L61-63

I have a directory structure like so:

```
views\
     viewName\
         index.dust
         header.dust
         footer.dust
```

I'd like to be able to write my template like this, in this case:

index.dust

```
{>header/}
Contents
{>footer/}
```

Trying to keep my templates separated as logical reusable components.

https://github.com/visionmedia/consolidate.js/blob/master/lib/consolidate.js#L146-150

Would you accept a patch that used options.filename to try a relative pathname for a partial before falling back to views + partial name + ext?

**Comment by mendlik** [comment]
+1

**Comment by doowb** [comment]
Sounds like this was resolved since partials are read relative from the view being rendered.
If there is a different implementation that needs to be added for the `dust` specific `onLoad` method, I'll review a PR for that.
