### ISSUE TITLE
Scope of consolidate.js -- precompilation?

### ISSUE THREAD

**Issue by jmoyers** [tj/consolidate.js#68]
Have you thought about exposing a consistent/consolidated compile/precompile api against the supported template engines?

I hacked something together yesterday:
https://github.com/jmoyers/dustfly

Goal is to provide both a command line tool and an express plugin to precompile a set of templates and expose the javascript via routes/static files with etags etc, and share those compiled templates on the server and client.

If I could use `require('consolidate')[engineName].precompile` that would be handy. Perhaps inside consolidate scope?

**Comment by erwan** [comment]
It'd be something I would love too, to have a generic way to compile templates for use in-browser. I'll probably take a shot at is and see where it brings me.

**Comment by doowb** [comment]
I'm going to close this for now, but if someone wants to do a PR that makes it easy across all engines, that'd be cool.
