### ISSUE TITLE
Exporting a `test_lang` so we can streamline our own language unit tests?

### ISSUE THREAD

**Issue by malgorithms** [tj/consolidate.js#91]
Hey TJ - 

I want to make sure Toffee never breaks support for consolidate.js. And I assume the other language maintainers feel the same way.

Normally this is the way I test Toffee, after making any change:
1. run my own test program, which checks the language syntax, etc.
2. get the latest consolidate
3. install the version of toffee I'm testing in consolidate.js's node_modules folder
4. `> consolidate.js/make test`

Steps 4 runs your unit test suite.

In my ideal world, as a language maintainer, I'd like to run one command to test my language.

So, is there/could there be some simple way for me to integrate your test function in my own program? 

``` javascript
require("consolidate").test_lang("toffee",  function(status) {
  // are things working?
});
```

This is something an author could do after they added their language to your consolidate.js file, not before; i.e., you would just expose a test_lang function that would call back with success or failure.

If there's another technique that's preferable, I'm game for that too.

-cc

**Comment by doowb** [comment]
`consolidate` doesn't publish the tests to npm and I don't think it should.

However, you can run tests just for your engine with a test file similar to this (customized for your engine):

**test/consolidate.js**
```js
'use strict';

// my engine to use and set it on the requires object
// so tests use the latest code
var myEngine = require('../');
var consolidate = require('./consolidate');
consolidate.requires['my-engine'] = myEngine;

// get all of the test files from consolidate
var shared = require('./consolidate/test/shared');
var filters = require('./consolidate/test/shared/filters');
var includes = require('./consolidate/test/shared/includes');
var partials = require('./consolidate/test/shared/partials');
var helpers = require('./consolidate/test/shared/helpers');

// run tests
shared.test('my-engine');
filters.test('my-engine');
includes.test('my-engine');
partials.test('my-engine');
helpers.test('my-engine');
```

Then you can clone `consolidate` and do NPM install to get the dependencies the tests need:

```sh
$ git clone https://github.com/tj/consolidate.js.git test/consolidate
$ cd test/consolidate && npm i
```
